#### Cadastrar novo usuario
POST http://localhost:3000/usuarios
Content-Type: application/json

{
    "nome": "Zelezim da Paraiba"
}

#### Listar usuarios
GET http://localhost:3000/usuarios

#### Localizar usuario por id
GET http://localhost:3000/usuarios/01

#### Alterar usuario
PUT http://localhost:3000/usuarios/03
Content-Type: application/json

{
    "nome": "Zé Lezim da Paraíba"
}

#### Excluir usuario
DELETE http://localhost:3333/usuarios/2


###
